### ISSUE TITLE
bug: Github Workflow doesn't find forge and anvil

### ISSUE THREAD

**Issue by MarcBickel** [scaffold-eth/scaffold-eth-2#682] opened 2024-01-11 12:25 UTC
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

npx create-eth@latest

### Current Behavior

When pushing to a github repo (created with the foundry branch), thus triggering the lint workflow, step "Run hardhat..." fails because the command `forge` and the command `anvil` are not found. 

### Expected Behavior

First, that the step in the workflow is called foundry, not hardhat. Second, that the workflow actually goes until the linting, and manages to go past the install step. 

### Steps To Reproduce

Just create a foundry version of this and try to push to a repo on github. 

### Anything else?

I allow myself to write this issue here, since I looked at forks of this repo, and it seems like no other fork pushes their code on github, so not sure if other people experienced in this problem as well. Apologies if it is a duplicate or similar. 

I tried to make it work with installing submodules etc, which obviously doesn't work. 
I managed to make it go a bit further by adding 
```
- name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
```

but then the env variables are not found `Failed to resolve env var `ETHERSCAN_API_KEY` in `${ETHERSCAN_API_KEY}`: environment variable not found`, which makes me think that the install doesn't use the correct folder, and therefore doesn't use the env file in the foundry folder. 

(yes foundry is in the node_modules, yarnlock, etc so it should get installed)

**Comment by technophile-04** [comment] 2024-01-12 17:01
Hey thanks @MarcBickel, could please look at it #607 as it is duplicate of this 🙌

Also check out https://github.com/scaffold-eth/Scaffold-ETH-DeFi-Challenges/pull/29 for example on how to configure it on your fork, reagarind env's you could add those in GitHub https://docs.github.com/en/actions/learn-github-actions/variables

closing this for now please free to ask if you face any issues 🙌

**Closed by technophile-04** 2024-01-12 17:01 UTC
