### ISSUE TITLE
bug: wagmi v2 useScaffoldWatchContractEvent doesn't work as expected 

### ISSUE THREAD

**Issue by rin-st** [scaffold-eth/scaffold-eth-2#838] opened 2024-05-03 19:54 UTC
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone, npx create-eth@latest

### Current Behavior

When using `useScaffoldWatchContractEvent` with a [watched](https://wagmi.sh/react/guides/migrate-from-v1-to-v2#removed-watch-property) hook or `useScaffoldEventHistory`, `onLogs` doesn't fire or fire sometimes. Tried to make it work, but no luck in `hardhat` and `foundry`, on `sepolia` it works from time to time. But `onError` from `useScaffoldWatchContractEvent` fires often.

Also tried to make an app without `<ScaffoldApp>` wrapper to minimize rerenders and logic that can cause the bug, used pure `wagmi` hook `useWatchContractEvent` and [watched](https://wagmi.sh/react/guides/migrate-from-v1-to-v2#removed-watch-property) `useBalance` on `hardhat`. Result - `onLogs` fires sometimes, but not in 100% of cases. So looks like it's on `wagmi` side. Raised an [issue](https://github.com/wevm/wagmi/issues/3883) .

Probably I'm missing something, so if you know what's wrong please let me know

### Expected Behavior

`onLogs` fires in 100% cases

### Steps To Reproduce

[Example](https://github.com/scaffold-eth/se-2-challenges/tree/challenge-3-wagmi-2-pure-app) of app without scaffold hooks (based on sre challenge 3). You'll need to start second app on localhost:3001 and send eth to your account from localhost:3000

[Example 2](https://github.com/scaffold-eth/se-2-challenges/tree/challenge-3-wagmi-2-example) with our hooks. Challenge 3 with wagmi v2 (working on this)

### Anything else?

see also last part of Shiv's message https://github.com/scaffold-eth/scaffold-eth-2/pull/700#issuecomment-2048117489

**Comment by ivanbaldo** [comment] 2024-07-22 19:32
If I understood correctly, I think this is not a bug on Scaffold-ETH nor Wagmi nor Viem but a shortcoming of free public RPC providers which don't store event filters forever and sometimes not even at all.
So maybe this issue should be closed?
Or perhaps some documentation (which?) could be enhanced to warn users about this shortcoming?

**Comment by technophile-04** [comment] 2024-07-23 08:16
Yup closing this and should be documented in https://github.com/scaffold-eth/se2-docs/pull/74, thanks all!!

**Closed by technophile-04** 2024-07-23 08:16 UTC
